---

- name: restart {{ superset_services.app.service_name }}
  systemd:
    name: "{{ superset_services.app.service_name }}"
    state: restarted
  when:
    - superset_services.app
    - superset_services.app.enabled

- name: restart {{ superset_services.celery_flower.service_name }}
  systemd:
    name: "{{ superset_services.celery_flower.service_name }}"
    state: restarted
  when:
    - superset_services.celery_flower
    - superset_services.celery_flower.enabled

- name: restart {{ superset_services.celery_worker.service_name }}
  systemd:
    name: "{{ superset_services.celery_worker.service_name }}"
    state: restarted
  when:
    - superset_services.celery_worker
    - superset_services.celery_worker.enabled

- name: restart {{ superset_services.celery_beat.service_name }}
  systemd:
    name: "{{ superset_services.celery_beat.service_name }}"
    state: restarted
  when:
    - superset_services.celery_beat
    - superset_services.celery_beat.enabled

- name: superset initialize db
  command: "./{{ superset_exec_name }} db upgrade"
  args:
    chdir: "{{ superset_bin_path }}"
  environment:
    SUPERSET_HOME: "{{ superset_app_home }}"
    SUPERSET_CONFIG_PATH: "{{ superset_config_file_path }}"

- name: superset sync db
  command: "./{{ superset_exec_name }} init"
  args:
    chdir: "{{ superset_bin_path }}"
  environment:
    SUPERSET_HOME: "{{ superset_app_home }}"
    SUPERSET_CONFIG_PATH: "{{ superset_config_file_path }}"
