---

- name: SUPERSET | Copy superset_config file
  template:
    src: superset_config.j2
    dest: "{{ superset_config_file_path }}"
    mode: 0775
    owner: "{{ superset_user }}"
    group: "{{ superset_group }}"
  register: superset_config
  notify:
    - "restart {{ superset_services.app.service_name }}"
    - "restart {{ superset_services.celery_flower.service_name }}"
    - "restart {{ superset_services.celery_worker.service_name }}"
    - "restart {{ superset_services.celery_beat.service_name }}"
  tags: config

- name: Initialize the db
  command: "./{{ superset_exec_name }} db upgrade"
  args:
    chdir: "{{ superset_bin_path }}"
  register: superset_db_init
  when: superset_install.changed or superset_config.changed  # noqa 503
  notify:
    - "restart {{ superset_services.app.service_name }}"
    - "restart {{ superset_services.celery_flower.service_name }}"
    - "restart {{ superset_services.celery_worker.service_name }}"
    - "restart {{ superset_services.celery_beat.service_name }}"

- name: List users
  command: "./{{ superset_exec_name }} fab list-users"
  args:
    chdir: "{{ superset_bin_path }}"
  register: superset_listed_users
  changed_when: false
  no_log: true
  tags: config

- name: SUPERSET | Create default roles and permissions
  command: "./{{ superset_exec_name }} init"
  args:
    chdir: "{{ superset_bin_path }}"
  when: superset_install.changed or superset_config.changed  # noqa 503
  tags: config

- name: SUPERSET | Create admin users
  command: "./{{ superset_exec_name }} fab create-admin --username {{ item.username }} --password {{ item.password }} --email {{ item.email }} --firstname {{ item.firstname }} --lastname {{ item.lastname }}"
  args:
    chdir: "{{ superset_bin_path }}"
  with_items: "{{ superset_admin_users }}"
  when: "'username:' ~ item.username not in superset_listed_users.stdout or superset_force_reinstall"
  notify:
    - superset sync db
  no_log: true
  tags: config

- name: SUPERSET | Create regular users
  command: "./{{ superset_exec_name }} fab create-user --username {{ item.username }} --password {{ item.password }} --role {{ item.role | default('Public') }} --email {{ item.email }} --firstname {{ item.firstname }} --lastname {{ item.lastname }}"
  args:
    chdir: "{{ superset_bin_path }}"
  with_items: "{{ superset_regular_users }}"
  when: "superset_regular_users is defined and 'username:' ~ item.username not in superset_listed_users.stdout or superset_force_reinstall"
  notify:
    - superset sync db
  no_log: true
  tags: config

- name: SUPERSET | Ensure db file superset_user has ownership
  file:
    path: "{{ superset_metadatadb_path }}/superset.db"
    owner: "{{ superset_user }}"
    group: "{{ superset_group }}"
    state: file
  when: superset_sqlalchemy_database_uri is search("sqlite")
  tags: config
